repos:
  # General hooks for common issues.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1024]

  # Python linting and formatting using ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  # Security checks using bandit.
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, -c, bandit.yaml]

  # YAML linting using yamllint.
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        args: [--strict, -c, .yamllint.yaml]

  # Markdown linting using markdownlint.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        files: \.(md|markdown)$
        args: [--config, .markdownlint.yaml]

  # Checks commit messages for Conventional Commits formatting.
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            --strict,
            --types,
            feat,
            fix,
            perf,
            build,
            chore,
            ci,
            docs,
            release,
            refactor,
            style,
            test,
          ]

  # Custom version consistency check.
  - repo: local
    hooks:
      - id: version-consistency
        name: Check version consistency
        entry: python scripts/check_version.py
        language: python
        stages: [pre-push]
