site_name: Scaffold Kit
site_description: >
  Command-line tools for project setup, structure creation, file tracking, and
  directory trees.
copyright: © 2025 Dirk Sidney Jansen. All Rights Reserved.
repo_name: sidisinsane/scaffold-kit
site_url: https://sidisinsane.github.io/scaffold-kit
repo_url: https://github.com/sidisinsane/scaffold-kit
docs_dir: docs
site_dir: site
dev_addr: 127.0.0.1:8888
edit_uri: edit/main/docs/
use_directory_urls: true

draft_docs: |
  draft.*.md

plugins:
  - mkdocs-nav-weight:
      section_renamed: true
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false
  - offline
  - search
  - autorefs
  - mkdocstrings

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/logo-dark-theme.svg
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty:
      smart_dashes: true
      smart_quotes: true
      smart_angled_quotes: true
      smart_ellipses: true
  - toc:
      permalink: "#"

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sidisinsane
