line-length = 80

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "dist",
  "node_modules",
  "venv",
  "uv.lock",
  "docs",
  "reports",
  "public",
]

[format]
docstring-code-format      = false
docstring-code-line-length = 80

[lint]
select = [
  "I",
  "E501", # line-too-long
  "W505", # doc-line-too-long
]

[lint.per-file-ignores]
"**/scripts/*" = [
  "I002",   # from __future__ import annotations
  "INP001",
  "T201",
]

"**/tests/**/*" = [ "PLC1901", "PLR2004", "PLR6301", "S", "TID252" ]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = [  ]
case-sensitive = true
length-sort-straight = true
lines-after-imports = 2
lines-between-types = 1
order-by-type = true
required-imports = [ "from __future__ import annotations" ]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses    = false

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
max-doc-length = 80
